#+TITLE: ivy-purpose
ivy-purpose provides specialized [[https://github.com/abo-abo/swiper/][Ivy]] commands for [[https://github.com/bmag/emacs-purpose/][Purpose]].

* Features
- make all Purpose commands use Ivy (when =ivy-mode= is on)
- special Ivy commands:
  + =ivy-purpose-switch-buffer-with-purpose=: same as =ivy-switch-buffer=, but
    only list buffers with a specific purpose (default: same purpose as current
    buffer).
  + =ivy-purpose-switch-buffer-with-some-purpose=: choose a purpose, then call
    =ivy-purpose-switch-buffer-with-purpose=.
  + =ivy-purpose-switch-buffer-without-purpose=: same as =ivy-switch-buffer=,
    but ignore Purpose when displaying the buffer.

* Setup
Just call =ivy-purpose-setup= in your init file. It will make all Purpose
commands use Ivy (when =ivy-mode= is on), but won't change any key bindings.
Alternatively, you can set =purpose-preferred-prompt= to =vanilla= instead.

* Key Bindings
=ivy-purpose= doesn't bind any keys, you are free to define your own bindings
as you please.
